// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcychhlzqylmotrzjkvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jeWNoaGx6cXlsbW90cnpqa3ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDI0OTQsImV4cCI6MjA2NDg3ODQ5NH0.0dEIlw9upgkFv5kwVV7wUP2Cs540l_P05wUBu32RNR0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);